---
jobs:
- name: job-hello-world
  public: true
  plan:
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: 04_basic_pipeline
      run:
        path: ./04_basic_pipeline/helloworld.sh
